---
sudo: false

language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

cache: bundler
bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

before_install: gem install bundler -v 2.0.2 --no-document
script:
  - bundle exec rake test
  - rubocop

notifications:
  email: false
