---
sudo: false

language: ruby
rvm:
  - 2.5
  - 2.6

cache: bundler
bundler_args: --jobs=3 --retry=3 --path=../vendor/bundle

before_install:
  - bundle exec rake webdrivers:chromedriver:update
  - gem install bundler -v 2.0.2 --no-document

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
