---
sudo: false

language: ruby
rvm:
  - 2.5
  - 2.6

cache: bundler
bundler_args: --jobs=3 --retry=3 --path=../vendor/bundle

after_install:
  - bundle exec rake webdrivers:chromedriver:update

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
