---
sudo: false

addons:
  chrome: stable

language: ruby
rvm:
  - 2.5
  - 2.6

cache: bundler

before_install:
  - gem update --system
  - gem install bundler --no-document

before_script:
  - bundle exec rake webdrivers:chromedriver:update

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
